# Generated by Django 2.1.5 on 2019-01-18 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
